# Site settings
title: Dima Markus
email: markus.dmitriy@gmail
description: > # this means to ignore newlines until "baseurl:"
  A UX designer who codes
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dimamarkus.com" # the base hostname & protocol for your site
twitter_username: dimamarkus
github_username:  dimamarkus

permalink: /:categories/:title

links:
  - title: about
    url: /about
  - title: work
    url: /work
  - title: articles
    url: /articles
  - title: hire me
    url: /hire-me


# Build settings
markdown: kramdown
